### ISSUE TITLE
MPEG2Video error to plex

### ISSUE THREAD

**Issue by CollabSensei** [cedarrapidsboy/pms-postprocessing#1]
When a video is already encoded a h.264, and "$ONLYMPEG2" is set, the script correctly does not process the file. However, it raises an error, which causes Plex to fail the recording. 

In testing, I changed it to simply echo the error message, and then exit 0. When the recording already encoded it should not process, but also not raise an error to plex.

**Comment by cedarrapidsboy** [comment]
Thanks @CollabSensei . I imagine you are referring to "exit {$1}" in the check_errs function. Is your change simply "exit 0;"?

Unfortunately, without a non-MPEG2 tuner, I have a hard time testing how Plex reacts to different returns. I appreciate your feedback.

Are you willing to confirm your change and submit a pull request? (or, just give me the modified code here)

**Comment by cedarrapidsboy** [comment]
I added the "do_nothing" function as an alternative to the "check_errs" function. The script now exits without an error code if this condition is met.
