### ISSUE TITLE
PMS version 1.20.0.3113 "unable to determine video dimensions"

### ISSUE THREAD

**Issue by bipple294** [cedarrapidsboy/pms-postprocessing#10]
I am on PMS 1.20.0.3113 and just installed your script with high hopes.  After copying the script to the scripts directory and specifying it in the DVR settings, i get the message below:

20200726-020119 [p3aEMX8D] INFO: transcode_internal.sh : Starting postprocessing for /DVR_Media/.grab/9dee844c194aa034cf1f0279c7eddaeaad92985d-3dc89e54a750dd6489d067d9ed0601d467db047a/Lost in Space (1965) - S02E15 - The Golden Man.ts.
20200726-020122 [p3aEMX8D] ERROR: transcode_internal.sh : Trasncode canceled. Unable to determine input video dimensions.
20200726-020122 [p3aEMX8D] INFO: transcode_internal.sh : Postprocessing completed. No work done. Removed /tmp/working.eUEiG4Nu.mkv.

I have confirmed the the script has the correct permissions and a umask of 0755.  I am running this in an unRaid docker container with NVENC enabled.

**Comment by cedarrapidsboy** [comment]
@bipple294 - can you run a couple commands in a BASH shell within your PMS container? Specifically,

Open BASH console in your PMS container (`docker exec -it <container name> /bin/bash`), then:

1) Copy the original TS file to the TMP folder
`# cd /tmp`
`# cp <original TS file> test.ts`

2) Setup the transcoding ENV variable and working file (like the script does)
`# export FFMPEG_EXTERNAL_LIBS="$(find ~/Library/Application\ Support/Plex\ Media\ Server/Codecs/ -name "libmpeg2video_decoder.so" -printf "%h\n")/"`
`# /usr/lib/plexmediaserver/Plex\ Transcoder -y -hide_banner -i test.ts -c:v copy -c:a copy -c:s copy -c:d copy -c:t copy working.mkv`

3) Run a few commands to test capturing the dimensions (please send the output of these commands)
`# /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv`
`# /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv 2>&1 | grep "Stream #0:0" | perl -lane 'print "$1 $2 $3" if /Video: (\w+) .+, (\d{3,})x(\d{3,})/'`
`# /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv 2>&1 | grep "Stream #0:0" | perl -lane 'print $1 if /, (\d+(.\d+)*) fps/'`

From your log, it is these commands that are not returning the expected dimensions and/or fps.

After you are done, you can delete the files we created in the /tmp folder.

**Comment by bipple294** [comment]
> 3\. /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv 2>&1 | grep "Stream #0:0" | perl -lane 'print $1 if /, (\d+(.\d+)*) fps/'

It looks like those commands are able to see the details of the test file.  

`sh-5.0# export FFMPEG_EXTERNAL_LIBS="$(find ~/Library/Application\ Support/Plex\ Media\ Server/Codecs/ -name "libmpeg2video_decoder.so" -printf "%h\n")/"
find: ‘/home/nobody/Library/Application Support/Plex Media Server/Codecs/’: No such file or directory
sh-5.0# /usr/lib/plexmediaserver/Plex\ Transcoder -y -hide_banner -i test.ts -c:v copy -c:a copy -c:s copy -c:d copy -c:t copy working.mkv
Input #0, mpegts, from 'test.ts':
  Duration: 00:08:15.52, start: 1.400000, bitrate: 10452 kb/s
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: mpeg2video ([2][0][0][0] / 0x0002), none(progressive), 1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 59.94 fps, 59.94 tbr, 90k tbn, 119.88 tbc
    Stream #0:1[0x101](eng): Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, 5.1(side), s16p, 384 kb/s
    Stream #0:2[0x102](spa): Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, stereo, s16p, 96 kb/s
Output #0, matroska, to 'working.mkv':
  Metadata:
    duration        : 495.518
    encoder         : Lavf58.27.104
    Stream #0:0: Video: mpeg2video (mpg2 / 0x3267706D), none(progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 59.94 fps, 59.94 tbr, 1k tbn, 90k tbc
    Stream #0:1(eng): Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, 5.1(side), s16p, 384 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=29625 fps=15318 q=-1.0 Lsize=  575875kB time=00:08:15.45 bitrate=9521.7kbits/s speed= 256x    
video:552341kB audio:23169kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.063424%
sh-5.0# ls
plexmediaserver-stderr---supervisor-vbaderwg.log  plexmediaserver-stdout---supervisor-una1nzx_.log  test.ts  transcode.20200726.log  transcode.20200727.log  working.mkv
sh-5.0# /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv
Input #0, matroska,webm, from 'working.mkv':
  Metadata:
    ENCODER         : Lavf58.27.104
  Duration: 00:08:15.49, start: 0.000000, bitrate: 9521 kb/s
    Stream #0:0: Video: mpeg2video, none(progressive), 1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 59.94 fps, 59.94 tbr, 1k tbn, 119.88 tbc (default)
    Metadata:
      DURATION        : 00:08:15.489000000
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), s16p, 384 kb/s (default)
    Metadata:
      DURATION        : 00:08:15.481000000
At least one output file must be specified
sh-5.0# /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv 2>&1 | grep "Stream #0:0" | perl -lane 'print "$1 $2 $3" if /Video: (\w+) .+, (\d{3,})x(\d{3,})/'
sh-5.0# /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv 2>&1 | grep "Stream #0:0" | perl -lane 'print $1 if /, (\d+(.\d+)*) fps/'
59.94
sh-5.0# `

**Comment by bipple294** [comment]
> @bipple294 - can you run a couple commands in a BASH shell within your PMS container? Specifically,
> 
> Open BASH console in your PMS container (`docker exec -it <container name> /bin/bash`), then:
> 
> 1. Copy the original TS file to the TMP folder
>    `# cd /tmp`
>    `# cp <original TS file> test.ts`
> 2. Setup the transcoding ENV variable and working file (like the script does)
>    `# export FFMPEG_EXTERNAL_LIBS="$(find ~/Library/Application\ Support/Plex\ Media\ Server/Codecs/ -name "libmpeg2video_decoder.so" -printf "%h\n")/"`
>    `# /usr/lib/plexmediaserver/Plex\ Transcoder -y -hide_banner -i test.ts -c:v copy -c:a copy -c:s copy -c:d copy -c:t copy working.mkv`
> 3. Run a few commands to test capturing the dimensions (please send the output of these commands)
>    `# /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv`
>    `# /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv 2>&1 | grep "Stream #0:0" | perl -lane 'print "$1 $2 $3" if /Video: (\w+) .+, (\d{3,})x(\d{3,})/'`
>    `# /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv 2>&1 | grep "Stream #0:0" | perl -lane 'print $1 if /, (\d+(.\d+)*) fps/'`
> 
> From your log, it is these commands that are not returning the expected dimensions and/or fps.
> 
> After you are done, you can delete the files we created in the /tmp folder.

**It looks like those are able to see the details of that test file.  See below:**

sh-5.0# export FFMPEG_EXTERNAL_LIBS="$(find ~/Library/Application\ Support/Plex\ Media\ Server/Codecs/ -name "libmpeg2video_decoder.so" -printf "%h\n")/"
find: ‘/home/nobody/Library/Application Support/Plex Media Server/Codecs/’: No such file or directory

sh-5.0# /usr/lib/plexmediaserver/Plex\ Transcoder -y -hide_banner -i test.ts -c:v copy -c:a copy -c:s copy -c:d copy -c:t copy working.mkv
Input #0, mpegts, from 'test.ts':
  Duration: 00:08:15.52, start: 1.400000, bitrate: 10452 kb/s
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: mpeg2video ([2][0][0][0] / 0x0002), none(progressive), 1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 59.94 fps, 59.94 tbr, 90k tbn, 119.88 tbc
    Stream #0:1[0x101](eng): Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, 5.1(side), s16p, 384 kb/s
    Stream #0:2[0x102](spa): Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, stereo, s16p, 96 kb/s
Output #0, matroska, to 'working.mkv':
  Metadata:
    duration        : 495.518
    encoder         : Lavf58.27.104
    Stream #0:0: Video: mpeg2video (mpg2 / 0x3267706D), none(progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 59.94 fps, 59.94 tbr, 1k tbn, 90k tbc
    Stream #0:1(eng): Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, 5.1(side), s16p, 384 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=29625 fps=15318 q=-1.0 Lsize=  575875kB time=00:08:15.45 bitrate=9521.7kbits/s speed= 256x    
video:552341kB audio:23169kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.063424%

sh-5.0# /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv
Input #0, matroska,webm, from 'working.mkv':
  Metadata:
    ENCODER         : Lavf58.27.104
  Duration: 00:08:15.49, start: 0.000000, bitrate: 9521 kb/s
    Stream #0:0: Video: mpeg2video, none(progressive), 1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 59.94 fps, 59.94 tbr, 1k tbn, 119.88 tbc (default)
    Metadata:
      DURATION        : 00:08:15.489000000
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), s16p, 384 kb/s (default)
    Metadata:
      DURATION        : 00:08:15.481000000
At least one output file must be specified

sh-5.0# /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv 2>&1 | grep "Stream #0:0" | perl -lane 'print "$1 $2 $3" if /Video: (\w+) .+, (\d{3,})x(\d{3,})/'

sh-5.0# /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv 2>&1 | grep "Stream #0:0" | perl -lane 'print $1 if /, (\d+(.\d+)*) fps/'
59.94

**Comment by cedarrapidsboy** [comment]
I think the problem is shown with the following line (thanks for running the commands):

`sh-5.0# /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv 2>&1 | grep "Stream #0:0" | perl -lane 'print "$1 $2 $3" if /Video: (\w+) .+, (\d{3,})x(\d{3,})/'`

It did not return any results. The simple reason was I had assumed a video codec of the format "abcdef (xyz)" and had not yet run into a video file that had a simple codec "abcdef" (e.g. "mpeg2video"). I updated the pattern matching to allow for additional codec details.

See the linked pull request if you'd like to try it. I have moved the altered version to my server and will accept the pull request when it passes local testing.

**Comment by bipple294** [comment]
> I think the problem is shown with the following line (thanks for running the commands):
> 
> `sh-5.0# /usr/lib/plexmediaserver/Plex\ Transcoder -hide_banner -i working.mkv 2>&1 | grep "Stream #0:0" | perl -lane 'print "$1 $2 $3" if /Video: (\w+) .+, (\d{3,})x(\d{3,})/'`
> 
> It did not return any results. The simple reason was I had assumed a video codec of the format "abcdef (xyz)" and had not yet run into a video file that had a simple codec "abcdef" (e.g. "mpeg2video"). I updated the pattern matching to allow for additional codec details.
> 
> See the linked pull request if you'd like to try it. I have moved the altered version to my server and will accept the pull request when it passes local testing.

I am now receiving the following error message:

20200727-100145 [a6H95Ba4] DEBUG: transcode_internal.sh : /DVR_Media/.grab/832903575193943ba3e53da44a9def1a2903815e-3dc89e54a750dd6489d067d9ed0601d467db047a/Live With Kelly and Ryan (2001) - S32E236 - Kiefer Sutherland; Michael Symon.ts;mpeg2video;1280;720;>
20200727-100145 [a6H95Ba4] WARNING: 1 : transcode_internal.sh : Fail-over to libx264.
20200727-100145 [a6H95Ba4] ERROR: 1 : transcode_internal.sh : Transcode failed.
20200727-100145 [a6H95Ba4] INFO: transcode_internal.sh : Postprocessing completed. No work done. Removed /tmp/working.261Z1uIW.mkv.

**Comment by cedarrapidsboy** [comment]
One step forward...

Thanks for the error message. It appears truncated (">" at the end of the line):

> 20200727-100145 [a6H95Ba4] DEBUG: transcode_internal.sh : /DVR_Media/.grab/832903575193943ba3e53da44a9def1a2903815e-3dc89e54a750dd6489d067d9ed0601d467db047a/Live With Kelly and Ryan (2001) - S32E236 - Kiefer Sutherland; Michael Symon.ts;mpeg2video;1280;720;>

In your TMPFOLDER, there should be a log file for the "a6H95Ba4" job. Could you attach that?

**Comment by bipple294** [comment]
> One step forward...
> 
> Thanks for the error message. It appears truncated (">" at the end of the line):
> 
> > 20200727-100145 [a6H95Ba4] DEBUG: transcode_internal.sh : /DVR_Media/.grab/832903575193943ba3e53da44a9def1a2903815e-3dc89e54a750dd6489d067d9ed0601d467db047a/Live With Kelly and Ryan (2001) - S32E236 - Kiefer Sutherland; Michael Symon.ts;mpeg2video;1280;720;>
> 
> In your TMPFOLDER, there should be a log file for the "a6H95Ba4" job. Could you attach that?

Attached:

[transcode.20200727.log](https://github.com/cedarrapidsboy/pms-postprocessing/files/4983011/transcode.20200727.log)

**Comment by cedarrapidsboy** [comment]
I put together a version with some rather verbose logging. Hopefully this can give us a clue regarding what it doesn't like about your recordings.

https://github.com/cedarrapidsboy/pms-postprocessing/tree/10-bugfix-video-details-parsing

The 2 logs I'd like to see are the `transcode.YYYMMDD.log` and `transcode.YYYMMDD.err`.

**Comment by bipple294** [comment]
> I put together a version with some rather verbose logging. Hopefully this can give us a clue regarding what it doesn't like about your recordings.
> 
> https://github.com/cedarrapidsboy/pms-postprocessing/tree/10-bugfix-video-details-parsing
> 
> The 2 logs I'd like to see are the `transcode.YYYMMDD.log` and `transcode.YYYMMDD.err`.

Attached both logs:

[transcode.20200727.log](https://github.com/cedarrapidsboy/pms-postprocessing/files/4984206/transcode.20200727.log)
[transcode.20200727.err.log](https://github.com/cedarrapidsboy/pms-postprocessing/files/4984207/transcode.20200727.err.log)

**Comment by cedarrapidsboy** [comment]
The problem may have to do with finding the right location of the `FFMPEG_EXTERNAL_LIBS`. I've included another standard location that the script checks. It now checks the following locations (recursively) for the library:

`/config/Library/Application Support/Plex Media Server/Codeqs/`
`/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Codecs/`

Also, you can override the location if you know where the `libmpeg2video_decoder.so` library resides.

E.g., if you have the library at `/some/folder/of/codecs/libmpeg2video_decoder.so`, then use the following environment variable on your system (or docker container):

`export FFMPEGLIBS=/some/folder/of/codecs/`

See the update on the branch: https://github.com/cedarrapidsboy/pms-postprocessing/tree/10-bugfix-video-details-parsing

As before, attach the logs if it still fails.

**Comment by bipple294** [comment]
> The problem may have to do with finding the right location of the `FFMPEG_EXTERNAL_LIBS`. I've included another standard location that the script checks. It now checks the following locations (recursively) for the library:
> 
> `/config/Library/Application Support/Plex Media Server/Codecs/`
> `/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Codecs/`
> 
> Also, you can override the location if you know where the `libmpeg2video_decoder.so` library resides.
> 
> E.g., if you have the library at `/some/folder/of/codecs/libmpeg2video_decoder.so`, then use the following environment variable on your system (or docker container):
> 
> `export FFMPEGLIBS=/some/folder/of/codecs/`
> 
> See the update on the branch: https://github.com/cedarrapidsboy/pms-postprocessing/tree/10-bugfix-video-details-parsing
> 
> As before, attach the logs if it still fails.

I think i got it working now.  I modified it to look at the directory where i found the codecs like you suggested.  And changed the temp folder, because the /tmp folder points to a folder on the RAM and that was "running out of space" when creating the working.mkv file.    

I attached the file for your records.    

Troubleshooting script:
[transcode_internal.txt](https://github.com/cedarrapidsboy/pms-postprocessing/files/4985845/transcode_internal.txt)

Modified master:
[transcode_internal.txt](https://github.com/cedarrapidsboy/pms-postprocessing/files/4986018/transcode_internal.txt)

Thanks for all your help!!!

**Comment by cedarrapidsboy** [comment]
Glad you got it working! I expected my codecs path would be pretty standard since I am using a PMS docker container myself... but, that was naive. Your modified script is a valid way to go (and, obviously, working). If you wanted to use the script _without_ hard-coding the codecs path, the FFMPEGLIBS variable can be set via an environment variable passed to the docker container. For instance:

    docker run \
    -d \
    --name plex \
    --network=host \
    -e TZ="<timezone>" \
    -e PLEX_CLAIM="<claimToken>" \
    -e FFMPEGLIBS="/config/Plex\ Media\ Server/Codecs" \
    -v <path/to/plex/database>:/config \
    -v <path/to/transcode/temp>:/transcode \
    -v <path/to/media>:/data \
    plexinc/pms-docker

I will be updating the released version of the script to support the FFMPEGLIBS environment variable and _quiet_ logging levels.

Thanks for helping me improve this script.
