### ISSUE TITLE
Hardware enabled Deinterlace

### ISSUE THREAD

**Issue by Xylaant** [cedarrapidsboy/pms-postprocessing#8]
Looking at the Plex Transcoder, there appears to be support for the yadif_cuda filter, which should let this decode cuda as well.  Any thoughts on how to get that in, or what issues it might cause?

**Comment by cedarrapidsboy** [comment]
I don't recall if I ever actually tried replacing yadif with yadif_cuda. I'll give it a go next time I have a chance and report back. Would make a lot of sense if nvdec/enc is used to also use it for deinterlacing.

**Comment by cedarrapidsboy** [comment]
@Xylaant 
Give the pull request a try on your end. For me, it successfully uses yadif_cuda for deinterlacing (~500fps vs. ~300fps). Also, if I force an error, it falls back to using normal old CPU encoding and deinterlacing.
